Portfolio_App/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = (
    [
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("photos/", include("photos.urls", namespace="photos")),
        path("quotes/", include("quotes.urls", namespace="quotes")),
        path(
            "notifications/", include("notifications.urls", namespace="notifications")
        ),
        path("todos/", include("todo.urls", namespace="todos")),
        path("tinymce/", include("tinymce.urls")),
        path("resetpassword/", include("resetpassword.urls")),
        path("admin/", admin.site.urls),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("test/", views.test, name="test"),
    path("health/", views.health, name="health"),
]

szymon/urls.py
from django.urls import path
from . import views


app_name = "szymon"

urlpatterns = [
    path("", views.index, name="index"),
    path("cat/", views.cat_photos, name="cat_photos"),
    path("dog/", views.dog_photos, name="dog_photos"),
    path("simon/", views.simon_photos, name="simon_photos"),
    path("special/", views.special_photos, name="special_photos"),
]

szymon/views.py
import os
import random

import requests
from django.conf import settings
from django.shortcuts import render
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

from core.decorators import group_required


def get_drive_photos(mode):
    creds = Credentials.from_service_account_info(
        {
            "type": "service_account",
            "project_id": settings.DRIVE_PROJECT_ID,
            "private_key_id": settings.DRIVE_PRIVATE_KEY_ID,
            "private_key": settings.DRIVE_PRIVATE_KEY,
            "client_email": settings.DRIVE_CLIENT_EMAIL,
            "client_id": settings.DRIVE_CLIENT_ID,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": settings.DRIVE_CLIENT_X509_CERT_URL,
        }
    )
    service = build("drive", "v3", credentials=creds)

    if mode == "simon":
        folder_id = os.getenv("DRIVE_SIMON_FOLDER")
    elif mode == "special":
        folder_id = os.getenv("DRIVE_SPECIAL_FOLDER")

    results = (
        service.files()
        .list(
            q=f"mimeType contains 'image/' and trashed=false and '{folder_id}' in parents",
            fields="nextPageToken, files(id, name, webViewLink)",
        )
        .execute()
    )
    items = results.get("files", [])

    random_photo_link = random.choice(items)["webViewLink"]
    img_id = random_photo_link.split("/")[-2]
    img_id = img_id.replace("d_", "")
    return f"https://drive.google.com/uc?id={img_id}"


def get_cat_photos():
    api_key = os.getenv("CAT_API_KEY")
    url = f"https://api.thecatapi.com/v1/images/search?api_key={api_key}"
    response = requests.get(url)
    cat = response.json()[0]
    return cat["url"]


def get_dog_photos():
    url = "https://dog.ceo/api/breeds/image/random"
    response = requests.get(url)
    dog_url = response.json()["message"]
    return dog_url


def render_photo(request, photo=None):
    return render(
        request,
        "szymon/index.html",
        {
            "photo_id": photo,
        },
    )


def index(request):
    return render_photo(request)


def cat_photos(request):
    photo = get_cat_photos()
    return render_photo(request, photo)


def dog_photos(request):
    photo = get_dog_photos()
    return render_photo(request, photo)


@group_required("special photos")
def special_photos(request):
    photo = get_drive_photos("special")
    return render_photo(request, photo)


@group_required("simon photos")
def simon_photos(request):
    photo = get_drive_photos("simon")
    return render_photo(request, photo)

szymon/templates/szymon/index.html
{% extends 'core/_base.html' %}
{% load custom_filters %}

{% block title %}Photos{% endblock %}


{% block content %}
<div class="h-screen mt-5 pt-2">
    <div class="text-center mb-3">

        <a class="px-4 py-2 mt-20 rounded bg-white text-blue-700 border border-blue-700 text-2xl"
            href="{% url 'szymon:cat_photos'  %}">CAT</a>

        <a class="px-4 py-2 mt-20 rounded bg-white text-blue-700 border border-blue-700 text-2xl"
            href="{% url 'szymon:dog_photos'  %}">DOG</a>

        {% if request.user|in_group:"simon photos" %}
        <a class="px-4 py-2 mt-20 rounded bg-white text-blue-700 border border-blue-700 text-2xl"
            href="{% url 'szymon:simon_photos'  %}">SIMON</a>
        {% endif %}

        {% if request.user|in_group:"special photos" %}
        <a class="px-4 py-2 mt-20 rounded bg-white text-blue-700 border border-blue-700 text-2xl"
            href="{% url 'szymon:special_photos'  %}">SPECIAL</a>
        {% endif %}
    </div>

    {% if photo_id %}
    <div class="w-full h-5/6 flex justify-center">
        <img class="h-5/6 m-auto" src="{{ photo_id }}" alt="random photo">
    </div>
    {% endif %}
</div>
{% endblock %}