Portfolio_App/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = (
    [
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("photos/", include("photos.urls", namespace="photos")),
        path("quotes/", include("quotes.urls", namespace="quotes")),
        path(
            "notifications/", include("notifications.urls", namespace="notifications")
        ),
        path("todos/", include("todo.urls", namespace="todos")),
        path("tinymce/", include("tinymce.urls")),
        path("resetpassword/", include("resetpassword.urls")),
        path("admin/", admin.site.urls),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, PasswordResetView
from .forms import LoginForm


app_name = "accounts"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path(
        "update_profile/<int:section_id>", views.update_profile, name="update_profile"
    ),
    path("change-gravatar/", views.change_gravatar, name="change_gravatar"),
    path("public-users", views.public_users, name="public_users"),
    path(
        "friend_request/<int:friend_id>",
        views.send_friend_request,
        name="friend_request",
    ),
]

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("test/", views.test, name="test"),
    path("health/", views.health, name="health"),
]

notifications/urls.py
from django.urls import path
from . import views


app_name = "notifications"


urlpatterns = [
    path("", views.index, name="index"),
    path(
        "notification/<int:notification_id>",
        views.notification_detail,
        name="notification_detail",
    ),
    path(
        "delete_notification/<int:notification_id>",
        views.delete_notification,
        name="delete_notification",
    ),
    path(
        "delete-notifications/",
        views.delete_all_notifications,
        name="delete_notifications",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    gravatar_link = models.URLField(null=True)
    friends = models.ManyToManyField("self", blank=True)
    requested_friends = models.ManyToManyField("self", symmetrical=False, blank=True)

    def __str__(self):
        return self.username

notifications/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Notification(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name="notifications", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    link = models.URLField()
    read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group


INPUT_CLASSES = "w-full py-4 px-6 rounded-xl"

User = get_user_model()


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": INPUT_CLASSES,
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": INPUT_CLASSES,
            }
        )
    )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email is already registered.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match.")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": INPUT_CLASSES,
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email address",
                "class": INPUT_CLASSES,
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": INPUT_CLASSES,
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": INPUT_CLASSES,
            }
        )
    )


class GravatarForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("gravatar_link",)

        widgets = {
            "gravatar_link": forms.URLInput(attrs={"class": INPUT_CLASSES}),
        }


class ProfileSection1Form(forms.ModelForm):
    public = forms.ChoiceField(
        choices=((True, "Public"), (False, "Private")), widget=forms.RadioSelect
    )

    def clean_username(self):
        current_user = self.instance
        username = self.cleaned_data.get("username")
        if User.objects.filter(username=username).exclude(pk=current_user.pk).exists():
            raise forms.ValidationError(
                "This username is already taken. Please choose a different one."
            )
        return username

    def clean_email(self):
        current_user = self.instance
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exclude(pk=current_user.pk).exists():
            raise forms.ValidationError(
                "This email is already registered. Please use a different one."
            )
        return email

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email")

        widgets = {
            "first_name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "last_name": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "username": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "email": forms.EmailInput(attrs={"class": INPUT_CLASSES, "required": True}),
        }

    def __init__(self, *args, **kwargs):
        try:
            public_bool = kwargs.pop("public_bool")
        except:
            public_bool = None

        super(ProfileSection1Form, self).__init__(*args, **kwargs)
        if public_bool != None:
            self.fields["public"].initial = public_bool


class ProfileSection2Form(forms.ModelForm):
    class Meta:
        model = User
        fields = ()

    quote_newsletter = forms.ChoiceField(
        choices=((True, "Yes"), (False, "No")),
        widget=forms.RadioSelect,
    )
    email_notifications = forms.ChoiceField(
        choices=((True, "Yes"), (False, "No")), widget=forms.RadioSelect
    )

    def __init__(self, *args, **kwargs):
        try:
            quote_bool = kwargs.pop("quote_bool")
        except:
            quote_bool = None

        try:
            email_bool = kwargs.pop("email_bool")
        except:
            email_bool = None

        super(ProfileSection2Form, self).__init__(*args, **kwargs)
        if quote_bool != None:
            self.fields["quote_newsletter"].initial = quote_bool
        if email_bool != None:
            self.fields["email_notifications"].initial = email_bool

accounts/views.py
import hashlib
import random
from os import getenv

from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import (
    CustomUserCreationForm,
    GravatarForm,
    ProfileSection1Form,
    ProfileSection2Form,
)

from notifications.models import Notification
from notifications.views import add_notification

USER = get_user_model()


def register_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            hash = hashlib.md5(str(random.getrandbits(128)).encode("utf-8")).hexdigest()
            user.gravatar_link = f"https://www.gravatar.com/avatar/{hash}?d=identicon"
            user.save()
        send_mail(
            subject="Register in My App",
            message=f"Thanks for registering {user.username.title()}. Hope you'll have fun.",
            from_email=getenv("EMAIL"),
            recipient_list=[user.email],
        )
        return redirect("/accounts/login")
    else:
        form = CustomUserCreationForm()
    return render(request, "accounts/register.html", {"form": form})


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("accounts:login"))


@login_required
def index(request):
    return render(request, "accounts/index.html")


@login_required
def profile(request):
    return render(request, "accounts/profile.html")


@login_required
def update_profile(request, section_id):
    def change_group(user, group, decision):
        if decision == "True" and not user.groups.filter(name=group.name).exists():
            group.user_set.add(user)
        elif decision == "False" and user.groups.filter(name=group.name).exists():
            group.user_set.remove(user)

    user = request.user

    if section_id == 1:
        if request.method == "POST":
            form = ProfileSection1Form(request.POST, instance=user)
            if form.is_valid():
                temp_user = form.save(commit=False)
                user.first_name = temp_user.first_name
                user.last_name = temp_user.last_name
                user.username = temp_user.username
                user.email = temp_user.email
                user.save()

                public = form.cleaned_data.get("public")
                group = Group.objects.filter(name="public account").first()
                change_group(user, group, public)

                return redirect(reverse("accounts:profile"))

        else:
            public_bool = request.user.groups.filter(name="public account").exists()
            form = ProfileSection1Form(instance=user, public_bool=public_bool)

    if section_id == 2:
        if request.method == "POST":
            form = ProfileSection2Form(request.POST)
            if form.is_valid():
                quote_newsletter = form.cleaned_data.get("quote_newsletter")
                quote_group = Group.objects.filter(name="quote newsletter").first()
                change_group(user, quote_group, quote_newsletter)

                email_notifications = form.cleaned_data.get("email_notifications")
                email_group = Group.objects.filter(name="email notifications").first()
                change_group(user, email_group, email_notifications)

                return redirect(reverse("accounts:profile"))
        else:
            quote_bool = request.user.groups.filter(name="quote newsletter").exists()
            email_bool = request.user.groups.filter(name="email notifications").exists()
            form = ProfileSection2Form(quote_bool=quote_bool, email_bool=email_bool)
        return render(
            request,
            "accounts/profile.html",
            {
                "form": form,
                f"section{section_id}": True,
            },
        )
    return render(
        request,
        "accounts/profile.html",
        {
            "form": form,
            f"section{section_id}": True,
        },
    )


@login_required
def change_gravatar(request):
    user = request.user
    if request.method == "POST":
        form = GravatarForm(request.POST)
        if form.is_valid():
            temp_user = form.save(commit=False)
            user.gravatar_link = temp_user.gravatar_link
            user.save()
            return redirect(reverse("accounts:profile"))
    else:
        form = GravatarForm(instance=user)
    return render(
        request,
        "accounts/grav_form.html",
        {
            "form": form,
        },
    )


@login_required
def public_users(request):
    public_users = USER.objects.filter(groups__name="public account").exclude(
        id=request.user.id
    )

    return render(
        request,
        "accounts/public_users.html",
        {
            "public_users": public_users,
        },
    )


@login_required
def send_friend_request(request, friend_id):
    def check(u1, u2):
        if (
            u1.requested_friends.filter(id=u2.id).exists()
            and u2.requested_friends.filter(id=u1.id).exists()
        ):
            u1.requested_friends.remove(u2)
            u2.requested_friends.remove(u1)
            u1.friends.add(u2)

            notification1 = Notification(
                user=u1,
                title="You got a new friend.",
                content=f"{u2.username.title()} became your friend. Let's chat!",
                link=f"/accounts/public-users#{u2.id}",
            )
            add_notification(notification1)
            notification2 = Notification(
                user=u2,
                title="You got a new friend.",
                content=f"{u1.username.title()} became your friend. Let's chat!",
                link=f"/accounts/public-users#{u1.id}",
            )
            add_notification(notification2)
        else:
            notification = Notification(
                user=u2,
                title="You have new friend request.",
                content=f"{u1.username.title()} has sent you a friend request. Let's check it!",
                link=f"/accounts/public-users#{u1.id}",
            )
            add_notification(notification)

    user = request.user
    new_friend = USER.objects.filter(id=friend_id).first()
    if (
        not user.friends.filter(id=new_friend.id).exists()
        and not user.requested_friends.filter(id=new_friend.id).exists()
    ):
        user.requested_friends.add(new_friend)
        check(user, new_friend)
    return redirect(reverse("accounts:public_users"))

notifications/views.py
from .models import Notification
from os import getenv
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse


def add_notification(notification):
    notification.save()

    if notification.user.groups.filter(name="email notifications").exists():
        send_mail(
            subject="New Notification",
            message=f"You received new notification. Go Check: https://web-production-7633.up.railway.app{notification.link}",
            from_email=getenv("EMAIL"),
            recipient_list=[notification.user.email],
        )
        return True
    return False


@login_required
def index(request):
    notifications = request.user.notifications.all().order_by("-date")

    return render(
        request,
        "notifications/index.html",
        {
            "notifications": notifications,
        },
    )


@login_required
def notification_detail(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    if notification.user != request.user:
        return render(
            request,
            "core/index.html",
            {
                "error": "This wasn't your notification!",
            },
        )
    if notification.read == False:
        notification.read = True
        notification.save()
    return render(
        request,
        "notifications/notification.html",
        {
            "notification": notification,
        },
    )


@login_required
def delete_notification(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    if notification.user != request.user:
        return render(
            request,
            "core/index.html",
            {
                "error": "This wasn't your notification!",
            },
        )
    notification.delete()
    return redirect(reverse("notifications:index"))


@login_required
def delete_all_notifications(request):
    notifications = Notification.objects.filter(user=request.user).all()
    for notification in notifications:
        notification.delete()
    return redirect(reverse("notifications:index"))

accounts/templates/accounts/grav_form.html
{% extends 'core/_base.html' %}

{% block title %}
Change Gravatar
{% endblock %}

{% block content %}
<div class="w-8/12 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Change Gravatar for {{ user.username }}</h1>
    <form action="{% url 'accounts:change_gravatar' %}" method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Gravatar Link</label><br>
            {{ form.gravatar_link }}
        </div>
        {% include 'core/_form_errors.html' %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

    </form>
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'core/_base.html' %}

{% block title %}
Users
{% endblock %}

{% block content %}
<a class="px-5 py-2 rounded bg-white text-blue-700 border border-blue-700 text-2xl"
    href="{% url 'accounts:public_users' %}">Public Users</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "core/_base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-9/12 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Log in</h1>
  <form action="." method="post">
    {% csrf_token %}

    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br>
      {{ form.password }}
    </div>
    {% include 'core/_form_errors.html' %}
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>

  </form>
  <p class="mt-5">Don't remember your Password?
    <a class="text-blue-800"
      href="{% url 'accounts:reset_password' %}">Reset here</a>
  </p>
</div>
{% endblock %}

accounts/templates/accounts/notifications.html
{% extends 'core/_base.html' %}

{% block title %}Notifications{% endblock %}
{% block head %}
<style>
    td {
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="text-center mb-5">
    <a class="px-5 py-2 rounded bg-white text-red-700 border border-red-700 text-2xl"
        href="{% url 'accounts:delete_notifications' %}">Delete all Notifications</a>
</div>
<div class="flex justify-center">
    <table class="bg-slate-100 border-separate border border-slate-500 border-spacing-2 w-10/12">
        <thead>
            <th>Title</th>
            <th>Date</th>
            <th>New</th>
        </thead>
        <tbody>
            {% for notification in notifications %}
            <tr id="{{ notification.id }}">
                <td><a class="text-blue-600" href="{% url 'accounts:notification_detail' notification.id %}">
                        {{ notification.title }}</a></td>
                <td>{{ notification.date }}</td>
                <td>
                    {% if notification.read %}
                    Read
                    {% else %}
                    Unread
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'core/_base.html' %}
{% load custom_filters %}

{% block title %}{{ user.username.title }}'s Profile{% endblock %}

{% block content %}
<div class="w-10/12 mx-auto bg-slate-200 rounded-lg p-2">
    <div class="flex">
        <div class="w-8/12 relative border border-gray-50 p-5 mb-2">
            {% if section1 %}
            <form action="{% url 'accounts:update_profile' 1 %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label class="inline-block mb-2 text-lg">First Name</label><br>
                    {{ form.first_name }}
                </div>
                <div class="mb-3">
                    <label class="inline-block mb-2 text-lg">Last Name</label><br>
                    {{ form.last_name }}
                </div>
                <div class="mb-3">
                    <label class="inline-block mb-2 text-lg">username</label><br>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    <label class="inline-block mb-2 text-lg">Email</label><br>
                    {{ form.email }}
                </div>
                <div class="mb-3">
                    <label class="inline-block mb-2 text-lg">Account: </label><br>
                    {% for radio in form.public %}
                    {{ radio }}
                    {% endfor %}
                </div>
                {% include 'core/_form_errors.html' %}
                <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            </form>
            {% else %}
            <div>
                <div class="text-3xl font-bold mb-2">Personal Info</div>
                <div class="text-xl font-semibold">{{ user.first_name.title }} {{ user.last_name.title }}
                    ({{ user.username }})</div>
                <div class="text-xl font-semibold my-1">{{ user.email }}</div>
                <div class="text-xl font-semibold my-1">Public account: {% if user|in_group:"public account" %}✅
                    {% else%}❌{% endif %}</div>
            </div>
            <a class="absolute bottom-1 right-1 text-blue-600" href="{% url 'accounts:update_profile' 1 %}">Edit</a>
            {% endif %}
        </div>
        <div class="w-4/12">
            <a href="{% url 'accounts:change_gravatar' %}" title="Change Gravatar">
                <img class="w-1/2 mx-auto rounded-full" src="{{user.gravatar_link}}" alt="gravatar">
            </a>
        </div>
    </div>

    <!-- SECTION 2 -->

    <div class="w-8/12 relative border border-gray-50 p-5 mb-2">
        {% if section2 %}
        <form action="{% url 'accounts:update_profile' 2 %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2 text-lg">Quote Newsletter: </label>
                {% for radio in form.quote_newsletter %}
                {{ radio }}
                {% endfor %}
                <br>
                <label class="inline-block mb-2 text-lg">Email about Notifications: </label>
                {% for radio in form.email_notifications %}
                {{ radio }}
                {% endfor %}
            </div>
            {% include 'core/_form_errors.html' %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
        {% else %}
        <div>
            <div class="text-3xl font-bold mb-2">Newsletters</div>
            <div class="text-xl font-semibold my-1">Quote Newsletter:
                {% if user|in_group:"quote newsletter" %}✅{% else %}❌{% endif %}
            </div>
            <div class="text-xl font-semibold my-1">Email about Notifications:
                {% if user|in_group:"email notifications" %}✅{% else %}❌{% endif %}
            </div>
            <a class="absolute bottom-1 right-1 text-blue-600" href="{% url 'accounts:update_profile' 2 %}">Edit</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/public_users.html
{% extends 'core/_base.html' %}
{% load custom_filters %}

{% block title %}Public Users{% endblock %}
{% block head %}
<style>
    td {
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}

<div class="flex justify-center">
    <table class="bg-slate-100 border-separate border border-slate-500 border-spacing-2 w-10/12">
        <thead>
            <th>Name</th>
            <th>Email</th>
            <th>Photo</th>
            <th>Friend</th>
        </thead>
        <tbody>
            {% for user in public_users %}
            <tr id="{{ user.id }}">
                {% if user.first_name %}
                <td>{{ user.first_name }}</td>
                {% else %}
                <td>{{ user.username }}</td>
                {% endif %}
                <td>{{ user.email }}</td>
                <td><img class="mx-auto" src="{{ user.gravatar_link }}" alt="user gravatar"></td>

                {% if request.user|friend:user.id %}
                <td><a class="text-blue-600" href="#">Chat</a></td>
                {% elif request.user|requested_friend:user.id %}
                <td>Waiting</td>
                {% elif user|requested_friend:request.user.id %}
                <td><a class="text-blue-600" href="{% url 'accounts:friend_request' user.id %}">Approve</a></td>
                {% else %}
                <td><a class="text-blue-600" href="{% url 'accounts:friend_request' user.id %}">Add Friend</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "core/_base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-9/12 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Sign up</h1>
  <form action="." method="post">
    {% csrf_token %}

    <div class="mb-3">
      <label class="inline-block mb-2">Username</label><br>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Email</label><br>
      {{ form.email }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password</label><br>
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Repeat Password</label><br>
      {{ form.password2 }}
    </div>
    {% include 'core/_form_errors.html' %}
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
  </form>
</div>
{% endblock %}