Portfolio_App/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = (
    [
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("photos/", include("photos.urls", namespace="photos")),
        path("quotes/", include("quotes.urls", namespace="quotes")),
        path(
            "notifications/", include("notifications.urls", namespace="notifications")
        ),
        path("todos/", include("todo.urls", namespace="todos")),
        path("tinymce/", include("tinymce.urls")),
        path("resetpassword/", include("resetpassword.urls")),
        path("admin/", admin.site.urls),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, PasswordResetView
from .forms import LoginForm


app_name = "accounts"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path(
        "update_profile/<int:section_id>", views.update_profile, name="update_profile"
    ),
    path("change-gravatar/", views.change_gravatar, name="change_gravatar"),
    path("public-users", views.public_users, name="public_users"),
    path(
        "friend_request/<int:friend_id>",
        views.send_friend_request,
        name="friend_request",
    ),
]

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("test/", views.test, name="test"),
    path("health/", views.health, name="health"),
]

core/views.py
from django.shortcuts import render, HttpResponse
from accounts.models import CustomUser
from quotes.models import Quote


def index(request):
    return render(request, "core/index.html")


def health(request):
    return HttpResponse("WORKING")


def test(request):
    return HttpResponse("Done")

core/templates/core/_base.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | My App</title>
    <link href="{% static 'css/output.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
    <style>
        .with-dot {
            position: relative;
        }

        .with-dot::after {
            content: '';
            position: absolute;
            top: 0.5rem;
            right: 0.5rem;
            width: 0.5rem;
            height: 0.5rem;
            background-color: red;
            border-radius: 50%;
        }
    </style>
</head>

<body>
    <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center justify-between">
                <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                    <!-- Mobile menu button-->
                    <button type="button"
                        class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                        aria-controls="mobile-menu" aria-expanded="false">
                        <span class="sr-only">Open main menu</span>
                        <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                        </svg>
                        <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                    <div class="flex flex-shrink-0 items-center">
                        <img class="block h-8 w-auto lg:hidden"
                            src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
                        <img class="hidden h-8 w-auto lg:block"
                            src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
                    </div>
                    <div class="hidden sm:ml-6 sm:block">
                        <div class="flex space-x-4">
                            <a href="/" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium"
                                aria-current="page">Dashboard</a>

                            <a href="{% url 'photos:index' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Photos</a>

                            <a href="{% url 'quotes:index' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Quotes</a>

                            <a href="{% url 'accounts:index' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Users</a>

                            <a href="{% url 'todo:index' %}"
                                class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Todo</a>
                        </div>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                    {% if request.user.username %}
                    <a href="{% url 'accounts:logout' %}"
                        class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                        aria-current="page">Logout</a>
                    <a type="button" class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800
                        {% if request.user|unread_notifications %} with-dot{% endif %}"
                        href="{% url 'notifications:index' %}">
                        <span class="sr-only">View notifications</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                            aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                        </svg>
                    </a>
                    <div class="relative ml-3">
                        <div>
                            <a href="{% url 'accounts:profile' %}"
                                class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 overflow-hidden"
                                id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <img src="{{ user.gravatar_link }}" title="{{ user.username }}" alt="gravatar"
                                    class="h-8 w-8 rounded">
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <a href="{% url 'accounts:register' %}"
                        class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                        aria-current="page">Register</a>
                    <a href="{% url 'accounts:login' %}"
                        class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
                        aria-current="page">Login</a>
                    {% endif %}

                </div>
            </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2">
                <a href="/" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium"
                    aria-current="page">Dashboard</a>

                <a href="{% url 'photos:index' %}"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Photos</a>

                <a href="{% url 'quotes:index' %}"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Quotes</a>

                <a href="{% url 'accounts:index' %}"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Users</a>

                <a href="{% url 'todo:index' %}"
                    class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Todo</a>
            </div>
        </div>
    </nav>
    <div class="w-8/12 mx-auto mt-5">
        {% block content %}
        {% endblock %}
    </div>


    <script>
        const mobileMenuButton = document.querySelector('[aria-controls="mobile-menu"]');
        const mobileMenu = document.getElementById('mobile-menu');

        mobileMenuButton.addEventListener('click', () => {
            const expanded = mobileMenuButton.getAttribute('aria-expanded') === 'true';
            mobileMenuButton.setAttribute('aria-expanded', !expanded);
            mobileMenu.classList.toggle('hidden', expanded);
        });
    </script>
    {% block script %}
    {% endblock %}
</body>

</html>

core/templates/core/_form_errors.html
{% if form.errors or form.non_field_errors %}
<div class="mb-3 p-6 bg-red-100 rounded-xd">
    {% for field in form %}
    {{ field.errors }}
    {% endfor %}
    {{ form.non_field_errors }}
</div>
{% endif %}

core/templates/core/index.html
{% extends 'core/_base.html' %}

{% block title %}
Dashboard
{% endblock %}


{% block content %}

{% if error %}
<div class="justify-center flex">
    <div id="error-popup"
        class="fixed top-50px w-1/2 bg-red-500 text-white px-4 py-3 text-center text-lg font-semibold rounded-3xl">
        {{ error }}
        <button id="disable-error-popup" class="ml-4 text-lg text-red-500 p-2 font-medium bg-white rounded">X</button>
    </div>
</div>
{% endif %}
<div class="mt-10">
    <img src="https://images.unsplash.com/photo-1680253987970-b08eaabe8527?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2232&q=80"
        alt="https://unsplash.com/photos/oRp1nYVY26M">
</div>

{% endblock %}

{% block script %}
<script>
    document.getElementById('disable-error-popup').addEventListener('click', function () {
        document.getElementById('error-popup').classList.add('hidden');
    });
</script>
{% endblock %}