Portfolio_App/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = (
    [
        path("", include("core.urls", namespace="core")),
        path("accounts/", include("accounts.urls", namespace="accounts")),
        path("photos/", include("photos.urls", namespace="photos")),
        path("quotes/", include("quotes.urls", namespace="quotes")),
        path(
            "notifications/", include("notifications.urls", namespace="notifications")
        ),
        path("todos/", include("todo.urls", namespace="todos")),
        path("tinymce/", include("tinymce.urls")),
        path("resetpassword/", include("resetpassword.urls")),
        path("admin/", admin.site.urls),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("test/", views.test, name="test"),
    path("health/", views.health, name="health"),
]

quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.index, name="index"),
    path("add-quote", views.add_quote, name="add_quote"),
    path("update-quote/<int:quote_id>", views.update_quote, name="update_quote"),
    path("display-quote/<int:quote_id>", views.index, name="display_quote"),
    path("favorite/<int:quote_id>", views.favorite_quote, name="favorite_quote"),
    path(
        "admin/approve-quotes", views.approve_quotes_panel, name="approve_quotes_panel"
    ),
    path(
        "admin/approve-quote/<int:quote_id>",
        views.approve_quote_panel,
        name="approve_quote_panel",
    ),
    path(
        "admin/approve-quote/<int:quote_id>/<str:decision>",
        views.approve_quote,
        name="approve_quote",
    ),
]

quotes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from tinymce import models as tinumce_models

User = model = get_user_model()


class Quote(models.Model):
    languages = (
        ("EN", "English"),
        ("PL", "Polish"),
    )

    approve_choices = (
        ("AP", "Approved"),
        ("WT", "Waiting"),
        ("RJ", "Rejected"),
    )

    title = models.CharField(max_length=50, unique=True, blank=True)
    content = tinumce_models.HTMLField(max_length=2000, unique=True, blank=True)
    author = models.CharField(max_length=50, blank=True)
    language = models.CharField(max_length=2, choices=languages, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    favorites = models.ManyToManyField(User, related_name="favorite_quotes", blank=True)
    public = models.BooleanField(default=False)
    approved = models.CharField(max_length=2, choices=approve_choices, default="WT")

    def __str__(self) -> str:
        return self.title

quotes/forms.py
from django import forms
from .models import Quote
from tinymce.widgets import TinyMCE

INPUT_CLASSES = "w-full py-4 px-6 rounded-xl"
CHECKBOX_CLASSES = (
    "absolute block w-6 h-6 rounded-full bg-white border-4 cursor-pointer right-0 top-0"
)


class QuoteForm(forms.ModelForm):
    def clean_title(self):
        current_quote = self.instance
        title = self.cleaned_data.get("title")
        if Quote.objects.filter(title=title).exclude(pk=current_quote.pk).exists():
            raise forms.ValidationError("Quote with this title already exists")
        return title

    def clean_content(self):
        current_quote = self.instance
        content = self.cleaned_data.get("content")
        if Quote.objects.filter(content=content).exclude(pk=current_quote.pk).exists():
            raise forms.ValidationError("Quote with this content already exists")
        return content

    class Meta:
        model = Quote
        fields = ("title", "content", "author", "language", "public")

        widgets = {
            "title": forms.TextInput(attrs={"class": INPUT_CLASSES, "required": True}),
            "author": forms.TextInput(attrs={"class": INPUT_CLASSES, "required": True}),
            "language": forms.Select(attrs={"class": INPUT_CLASSES, "required": True}),
            "content": TinyMCE(attrs={"class": INPUT_CLASSES}),
            "public": forms.CheckboxInput(attrs={"class": CHECKBOX_CLASSES}),
        }


class QuoteSearchForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ("title", "content", "author", "language")

        widgets = {
            "title": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "author": forms.TextInput(attrs={"class": INPUT_CLASSES}),
            "language": forms.Select(attrs={"class": INPUT_CLASSES}),
            "content": forms.TextInput(attrs={"class": INPUT_CLASSES}),
        }

    is_favorite = forms.BooleanField(
        label="Is favorite",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": CHECKBOX_CLASSES}),
    )
    added_by_current_user = forms.BooleanField(
        label="Added by me",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": CHECKBOX_CLASSES}),
    )

    def search(self, user, get_all_quotes):
        # Build a queryset with the selected filters
        queryset = get_all_quotes(user)
        if self.cleaned_data["title"]:
            queryset = queryset.filter(title__iregex=self.cleaned_data["title"])
        if self.cleaned_data["content"]:
            queryset = queryset.filter(content__iregex=self.cleaned_data["content"])
        if self.cleaned_data["author"]:
            queryset = queryset.filter(author__iregex=self.cleaned_data["author"])
        if self.cleaned_data["language"]:
            queryset = queryset.filter(language=self.cleaned_data["language"])
        if self.cleaned_data["is_favorite"]:
            queryset = queryset.filter(favorites=user)
        if self.cleaned_data["added_by_current_user"]:
            queryset = queryset.filter(user=user)

        # Return a random quote from the resulting queryset
        return queryset.order_by("?").first()

quotes/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse
from django.db.models import Q

from accounts.models import CustomUser
from core.decorators import group_required

from .forms import QuoteSearchForm, QuoteForm
from .models import Quote

from notifications.models import Notification
from notifications.views import add_notification


def get_all_quotes(user):
    return Quote.objects.filter(Q(public=True, approved="AP") | Q(user=user)).all()


@group_required("quotes")
def index(request, quote_id=None):
    if quote_id:
        try:
            quote = Quote.objects.get(id=quote_id)
        except:
            return render(
                request,
                "core/index.html",
                {"error": f"Quote with id {quote_id} doesn't exist."},
            )
        form = QuoteSearchForm()
    else:
        if request.method == "POST":
            form = QuoteSearchForm(request.POST)
            if form.is_valid():
                quote = form.search(request.user, get_all_quotes)
        else:
            form = QuoteSearchForm()
            quote = get_all_quotes(request.user).order_by("?").first()

    context = {
        "form": form,
        "quote": quote,
    }
    return render(request, "quotes/index.html", context)


@group_required("quotes")
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user
            quote.save()
            if quote.public == False:
                quote.approved = "AP"
                quote.save()
            elif quote.public == True:
                notification = Notification(
                    user=request.user,
                    title="Your new quote is waiting for approval.",
                    content=f"Your new quote ({quote.title}) is waiting for approval. We are going to inform you after next steps.",
                    link=f"/quotes/display-quote/{quote.id}",
                )
                add_notification(notification)

                for user in CustomUser.objects.filter(groups__name="approve quotes"):
                    notification = Notification(
                        user=user,
                        title="New quote is waiting for approval.",
                        content=f"New quote ({quote.title}) is waiting for approval.",
                        link=f"/quotes/admin/approve-quotes#{quote.id}",
                    )
                    add_notification(notification)

            return redirect(reverse("quotes:display_quote", args=[quote.id]))
    else:
        form = QuoteForm()
    return render(request, "quotes/add_quote.html", {"form": form})


@group_required("quotes")
def favorite_quote(request, quote_id):
    quote = Quote.objects.get(id=quote_id)
    if request.user.favorite_quotes.filter(id=quote_id).exists():
        request.user.favorite_quotes.remove(quote)
    else:
        request.user.favorite_quotes.add(quote)
    return redirect(reverse("quotes:display_quote", args=[quote.id]))


@group_required("approve quotes")
def approve_quotes_panel(request):
    quotes_to_approve = Quote.objects.filter(approved="WT")

    return render(
        request,
        "quotes/approve_quotes_panel.html",
        {
            "quotes": quotes_to_approve,
        },
    )


@group_required("approve quotes")
def approve_quote_panel(request, quote_id):
    quote = Quote.objects.get(id=quote_id)

    return render(
        request,
        "quotes/approve_quote_details.html",
        {
            "quote": quote,
        },
    )


@group_required("approve quotes")
def approve_quote(request, quote_id, decision):
    quote = Quote.objects.get(id=quote_id)

    if decision == "Approve":
        quote.approved = "AP"
        title = "Your new quote has been approved."
        message = f"Your new quote ({quote.title}) has been approved. We think it's going to enrich our collection."
    elif decision == "Reject":
        quote.approved = "RJ"
        title = "Your new quote has been rejected."
        message = f"Your new quote ({quote.title}) has been rejected. It didn't match our standards."

    quote.save()

    notification = Notification(
        user=quote.user,
        title=title,
        content=message,
        link=f"/quotes/display-quote/{quote.id}",
    )
    add_notification(notification)

    return redirect(reverse("quotes:approve_quotes_panel"))


@group_required("quotes")
def update_quote(request, quote_id):
    quote = Quote.objects.get(id=quote_id)
    if request.method == "POST":
        form = QuoteForm(request.POST, instance=quote)
        if form.is_valid():
            temp_quote = form.save(commit=False)
            quote.user = request.user
            quote.title = temp_quote.title
            quote.author = temp_quote.author
            quote.language = temp_quote.language
            quote.public = temp_quote.public
            quote.content = temp_quote.content
            quote.approved = "WT"
            quote.save()
            if temp_quote.public == False:
                quote.approved = "AP"
                quote.save()
            elif temp_quote.public == True:
                notification = Notification(
                    user=request.user,
                    title="Your updated quote is waiting for approval.",
                    content=f"Your new quote ({quote.title}) is waiting for approval. We are going to inform you after next steps.",
                    link=f"/quotes/display-quote/{quote.id}",
                )
                add_notification(notification)

                for user in CustomUser.objects.filter(groups__name="approve quotes"):
                    notification = Notification(
                        user=user,
                        title="New quote is waiting for approval.",
                        content=f"New quote ({quote.title}) is waiting for approval.",
                        link=f"/quotes/admin/approve-quotes#{quote.id}",
                    )
                    add_notification(notification)

            return redirect(reverse("quotes:display_quote", args=[quote.id]))
    else:
        form = QuoteForm(instance=quote)
    return render(request, "quotes/add_quote.html", {"form": form, "quote": quote})


def daily_quote():
    quote = Quote.objects.order_by("?").first()
    newsletter_users = CustomUser.objects.filter(groups__name="quote newsletter")

    send_mail(
        subject="Quote Newsletter",
        message=f"Here's todays quote:\n{quote.title}\n@{quote.author}\n{quote.content}",
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[user.email for user in newsletter_users],
        html_message=f"Here's todays quote:\n{quote.title}\n@{quote.author}\n{quote.content}",
    )

quotes/templates/quotes/add_quote.html
{% extends 'core/_base.html' %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block title %}
{% if quote %}
Update Quote {{quote.id}}
{% else %}
Add Quote
{% endif %}
{% endblock %}

{% block content %}
<div class="w-8/12 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Add Quote</h1>
    <form method="post" {% if quote %} action="{% url 'quotes:update_quote' quote.id %}" {% else %}
        action="{% url 'quotes:add_quote' %}" {% endif %}>

        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Quote Title</label><br>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Quote Author</label><br>
            {{ form.author }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Quote Language</label><br>
            {{ form.language }}
        </div>
        <div class="mb-3 relative">
            <label class="inline-block mb-2">Public</label><br>
            {{ form.public }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Quote</label><br>
            {{ form.content }}
        </div>
        {% include 'core/_form_errors.html' %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

quotes/templates/quotes/approve_quote_details.html
{% extends 'core/_base.html' %}

{% block title %}Quote to Approve {{ notification.id }}{% endblock %}

{% block content %}
<div class="grid grid-cols-2">
    <div>
        <h1 class="text-3xl font-semibold mb-5">{{ quote.title }}</h1>
        <h2 class="text-xl mb-10">{{ quote.date }}</h2>
        <p>{{ quote.content|safe }}</p>
    </div>
    <div>
        <a class="px-4 py-2 rounded bg-white text-green-700 border border-green-700 text-2xl"
            href="{% url 'quotes:approve_quote' quote.id 'Approve' %}">Approve</a>
        <a class="px-4 py-2 rounded bg-white text-red-700 border border-red-700 text-2xl"
            href="{% url 'quotes:approve_quote' quote.id 'Reject' %}">Reject</a>
    </div>
</div>
{% endblock %}

quotes/templates/quotes/approve_quotes_panel.html
{% extends 'core/_base.html' %}

{% block title %}Approve Quotes{% endblock %}
{% block head %}
<style>
    td {
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<h1 class="text-3xl text-center font-semibold">ADMIN</h1>
<div class="flex justify-center">
    <table class="bg-slate-100 border-separate border border-slate-500 border-spacing-2 w-10/12">
        <thead>
            <th>Title</th>
            <th>Date</th>
        </thead>
        <tbody>
            {% for quote in quotes %}
            <tr id="{{ quote.id }}">
                <td><a class="text-blue-600" href="{% url 'quotes:approve_quote_panel' quote.id %}">
                        {{ quote.title }}</a></td>
                <td>{{ quote.added }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

quotes/templates/quotes/index.html
{% extends 'core/_base.html' %}

{% load custom_filters %}

{% block title %}Quotes{% endblock %}

{% block content %}
<div class="flex justify-between">
    <div class="w-4/12 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Search Quote</h1>
        <form action="{% url 'quotes:index' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Title</label><br>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Content</label><br>
                {{ form.content }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Author</label><br>
                {{ form.author }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Quote Language</label><br>
                {{ form.language }}
            </div>

            <div class="mb-3">
                <div class="relative inline-block w-full">
                    <label class="inline-block mb-2">Is Favorite</label>
                    {{ form.is_favorite }}
                </div>
            </div>

            <div class="mb-3">
                <div class="relative inline-block w-full">
                    <label class="inline-block mb-2">Added by Me
                        {{ form.added_by_current_user }}
                    </label>
                </div>
            </div>
            {% include 'core/_form_errors.html' %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Generate
                Quote</button>

        </form>
    </div>

    <div class="w-7/12">
        {% if quote %}
        <h2 class="text-2xl font-semibold mb-2">{{ quote.title }}
            <a href="{% url 'quotes:favorite_quote' quote.id %}">{% if request.user|favorite_quote:quote.id %}★
                {% else%}☆{% endif %}
            </a>
        </h2>
        <h3 class="text-lg mb-2">@{{ quote.author }}</h3>
        <p> {{ quote.content|safe }}</p>
        {% else %}
        <h1 class="text-3xl font-semibold">No Quotes matching selected filters.</h1>
        {% endif %}
        <div class="flex">
            <div class="mt-20">
                {% if quote %}
                <a href="{% url 'quotes:update_quote' quote.id %}"
                    class="px-4 py-2 rounded bg-white text-blue-700 border border-blue-700 text-2xl">Update
                    Quote</a>
                {% endif %}
                <a href="{% url 'quotes:index' %}"
                    class="px-4 py-2 rounded bg-white text-blue-700 border border-blue-700 text-2xl">Random Quote</a>
                <a href="{% url 'quotes:add_quote' %}"
                    class="px-4 py-2 rounded bg-white text-blue-700 border border-blue-700 text-2xl">Add Quote</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}